name: mlops-sample-project
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        python-version: ["pypy3.9", "pypy3.10", "3.9", "3.10", "3.11", "3.12"]
    #container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v4
      - name: 'make dataset ready'
      - uses: actions/setup-python@v5
       with:
          python-version:  ${{ matrix.python-version }}
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python src/data_ingestion.py
          
          # echo "## Model Metrics" > report.md
          # cat metrics.txt >> report.md
          
