# name: mlops-sample-project
# on: [push]
# jobs:
#   run:
#     runs-on: [ubuntu-latest]
    
#     container: docker://dvcorg/cml-py3:latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: 'make dataset ready'
#       #- uses: actions/setup-python@v5
#        with:
#           python-version:  3.9
#         env:
#           repo_token: ${{ secrets.GITHUB_TOKEN }}
#         run: |

#           # Your ML workflow goes here
#           pip install -r requirements.txt
#           python src/data_ingestion.py
          
#           # echo "## Model Metrics" > report.md
#           # cat metrics.txt >> report.md
          
name: Python application  
  
on:  
  push:  
    branches: [ dev ]  
  
jobs:  
  build:  
  
    runs-on: ubuntu-latest  
  
    steps:  
    - uses: actions/checkout@v2  
    - name: Set up Python 3.9  
      uses: actions/setup-python@v2  
      with:  
        python-version: 3.9  
      env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies  
      run: |  
        python -m pip install --upgrade pip  
        pip install -r requirements.txt  
    - name: Ingest Data  
      run: |  
        python src/data_ingestion.py
        git config --global user.name 'Amol suradkar'
        git config --global user.email 'amol2808suradkar@gmail.com'
        git add .
        git commit -m "data ingestion completed" 
        git push origin dev
    # - name: List changes  
    #   run: |  
    #     git config --global user.name 'Amol suradkar'
    #     git config --global user.email '36931368+amolsuradkar@users.noreply.github.com'
    #     echo "Changes:"  
    #     git status  
    #     echo "Diff:"  
    #     git diff  
  
    # - name: push data to repo
    #   run: |
    #     git config --global user.name 'Amol suradkar'
    #     git config --global user.email '36931368+amolsuradkar@users.noreply.github.com'
    #     git add .
    #     git commit -m "data ingestion completed" 
    #     git push origin dev
